In [1]:
import numpy as np
import sympy as sp

import ProGED as pg

In [4]:
ex1 = "C*C*x - C**2*x*y"
ex2 = "C*x*y - sin(C*y) + C + C*x/x"
symbols = {"x": ["x", "y"], "const": "C"}

In [5]:
models = pg.ModelBox()#observed=["x"])
models.add_system([ex1, ex2], symbols=symbols)
models

ModelBox: 1 models
-> [C0*x*y + C1*x, C2*x*y + C3 - sin(C4*y)], p = 1.0, parse trees = 1, valid = False

In [6]:
print(models[0].observed)
print(models[0].params)
print(models[0].initials)

['x', 'y']
[[-2.2827192110236294, -0.5220500192760291], [-2.486375032210999, 4.743761302187823, 3.652656957253874]]
[]


In [8]:
models[0].set_params([1,2,3,4,5])
print(models[0].params)
print(models[0].initials)

[array([1, 2]), array([3, 4, 5])]
[]


In [10]:
models[0].get_all_params()

[1, 2, 3, 4, 5]

In [23]:
f = models[0].lambdify()

In [24]:
X = np.random.random((10, 2))

In [25]:
f(X[0])

array([-0.64150578,  1.54836582])

In [3]:

grammar = pg.grammar_from_template("polynomial", 
    generator_settings = {"variables": ["'x'", "'y'", "'z'"], "p_vars": [1/3, 1/3, 1/3], "functions": [], "p_F": []})
symbols = {"x": ["x", "y", "z"], "const": "C"}

In [4]:
models = pg.generate.generate_models(grammar, symbols, dimension=3, observed = ["y"])

In [9]:
models[1].set_params([1,2,3,4,5,6])

In [12]:
models[1].get_params()

[array([1]), array([2]), array([3, 4])]

In [19]:
for m in models:
    f = m.lambdify()
    print(f(X))

[[ 1.22035004 -2.46075396 -0.83490272]
 [ 1.20497805 -2.42975739 -0.4326985 ]
 [ 1.33159333 -2.68506859 -0.41180011]
 [ 1.69581757 -3.41950233 -0.97326203]]
[[-1.40435946 -1.97430848  0.15959577]
 [-1.38666963 -1.02320942  0.15758544]
 [-1.53237647 -0.97379064  0.17414402]
 [-1.95151995 -2.30148906  0.22177678]]
[[-7.17634455 -0.43258778 -1.05466993]
 [-6.04628702 -0.22705394 -0.64252403]
 [-5.8730234  -0.19554091 -0.13669442]
 [-6.79312797 -0.36288869 -0.50676898]]
[[-0.88945027  1.97768982  1.48493025]
 [-0.69251819  1.02496185  1.45315711]
 [-0.01825918  0.97545843  1.71486464]
 [-0.35009791  2.30543076  2.4676982 ]]
[[-0.09155708  0.86937905 -0.39326157]
 [-0.04876953  1.30607815 -0.59080138]
 [ 0.11356512  0.03618413 -0.01636781]
 [ 0.0713601   0.2935507  -0.13278697]]


In [6]:
models = pg.ModelBox(observed=["y"])
models.add_model("x - C*y", {"x":["x", "y"], "const":"C"})

(True, 'C0*y + x')

In [7]:
a = [1,2,3]
[par for eq_params in a for par in eq_params]

TypeError: 'int' object is not iterable